# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "091e6b640a9e6d5098308de7a2d36a46"
application_url = "https://roles-authority-blackberry-expenses.trycloudflare.com"
embedded = true
name = "headless-checkout"
handle = "headless-checkout-001"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-commerce-grkggo3y.myshopify.com"

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_checkout_branding_settings,write_checkout_branding_settings,write_files"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://roles-authority-blackberry-expenses.trycloudflare.com/auth/callback",
  "https://roles-authority-blackberry-expenses.trycloudflare.com/auth/shopify/callback",
  "https://roles-authority-blackberry-expenses.trycloudflare.com/api/auth/callback"
]
